// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDec198azFvvR764wQs0XLG2kP17-60Sbo',
    appId: '1:920231916895:web:dce451b56ebef203b372ea',
    messagingSenderId: '920231916895',
    projectId: 'listahan-proj',
    authDomain: 'listahan-proj.firebaseapp.com',
    storageBucket: 'listahan-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqDm5UKcWGezm6t85avdO1njjsCCHpoHs',
    appId: '1:920231916895:android:09ff41dc32734ce0b372ea',
    messagingSenderId: '920231916895',
    projectId: 'listahan-proj',
    storageBucket: 'listahan-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaRw-yuX_oWdY8ybPcrcSQjnQEHAVD8HM',
    appId: '1:920231916895:ios:e9907b5b09d6fe61b372ea',
    messagingSenderId: '920231916895',
    projectId: 'listahan-proj',
    storageBucket: 'listahan-proj.appspot.com',
    iosClientId: '920231916895-39cpgnir76qpg1r27qvlf5cp716fh2qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.listahanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaRw-yuX_oWdY8ybPcrcSQjnQEHAVD8HM',
    appId: '1:920231916895:ios:e9907b5b09d6fe61b372ea',
    messagingSenderId: '920231916895',
    projectId: 'listahan-proj',
    storageBucket: 'listahan-proj.appspot.com',
    iosClientId: '920231916895-39cpgnir76qpg1r27qvlf5cp716fh2qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.listahanApp',
  );
}
